apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pod-selector
spec:
  podSelector:
    matchLabels:
      app: database
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: webserver
    ports:
      - port: 80
